name: Build image and deploy
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: digitalrelay/digital-relay-server
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'digitalrelay-dev'
          images: 'digitalrelay/digital-relay-server:latest'
      - name: Run latest version to generate OpenAPI specs
        run: docker run -p 80:80 -d -e port=80 digitalrelay/digital-relay-server
      - name: Generate OpenAPI Angular client
        run: docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i http://localhost/api/swagger.json -l typescript-angular -o /local/out/digital-relay-api-client -DpackageName=digital-relay-api-client -DprojectName=digital-relay-api-client
      - name: Push new Angular client client
        working-directory: ./local/out/digital-relay-api-client
        #        TODO: Add token to GIT enviroment
        run: ./git_push.sh <organization_id> digital-relay-api-client "${GITHUB_REF}"